version: 2.1

references:
  images:
    go: &GOLANG_IMAGE circleci/golang:latest

# reusable 'executor' object for jobs
executors:
  go:
    docker:
      - image: *GOLANG_IMAGE

jobs:
  release:
    executor: go
    working_directory: /go/src/github.com/ncabatoff/go-getter
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  release:
    jobs:
      - release:
          context: github
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
